export const ActionTypes = {
    SET_ALL_BOOKS :"SET_ALL_BOOKS",
    SET_SEARCHED_BOOKS : "SET_SEARCHED_BOOKS",
    SET_CART_BOOKS : "SET_CART_BOOKS",
    SET_ADD_CART_BOOKS :"SET_ADD_CART_BOOKS",
    SET_UPDATE_NOTE : "SET_UPDATE_NOTE"
}