export const ActionTypes = {
    SET_ALL_BOOKS :"SET_ALL_BOOKS",
    SET_SEARCHED_BOOKS : "SET_SEARCHED_BOOKS",
    SET_CART_BOOKS : "SET_CART_BOOKS",
    SET_ADD_CART_BOOKS :"SET_ADD_CART_BOOKS",
    SET_UPDATE_BOOK : "SET_UPDATE_BOOK",
    SET_DELETE_BOOK : "SET_DELETE_BOOK" ,
    SET_ORDER_ID : "SET_ORDER_ID",

}